chore(script): add git history test script
americanexpress/redux-idle-callback pull request #4
Opened 2020-03-05 22:55 UTC by JamesSingleton

2020-03-06 17:12 UTC, mtomcal submitted a review, later dismissed

2020-03-06 18:11 UTC, Francois-Esquire approved these changes

2020-03-06 18:46 UTC, Francois-Esquire approved these changes

2020-03-06 18:47 UTC, Francois-Esquire requested changes

2020-03-06 18:47 UTC, Francois-Esquire commented on package.json
> +  "dependencies": {},
Can we remove this key?

2020-03-10 22:27 UTC, 10xLaCroixDrinker approved these changes

2020-03-11 13:57 UTC, Francois-Esquire approved these changes

2020-03-11 13:59 UTC, merged